version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - "./infra/init-db:/docker-entrypoint-initdb.d"
      - "pgdata:/var/lib/postgresql/data"
    ports: [ "5434:5432" ]

  redis:
    image: redis:7
    ports: [ "6379:6379" ]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio12345}
    ports: [ "9000:9000", "9001:9001" ]

  rabbitmq:
    image: rabbitmq:3-management
    ports: [ "5672:5672", "15672:15672" ]

  auth-service:
    build: ./services/auth-service
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/auth
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-dev-access-secret}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-dev-refresh-secret}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
    depends_on: [ postgres ]

  catalog-service:
    build: ./services/catalog-service
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/catalog
    depends_on: [ postgres ]

  order-service:
    build: ./services/order-service
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/orders
      CATALOG_SERVICE_URL: http://catalog-service:4002
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on: [ postgres, rabbitmq, catalog-service ]

  notification-service:
    build: ./services/notification-service
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASS: ${SMTP_PASS:-}
      SMTP_FROM: ${SMTP_FROM:-orders@novaterra.apparel}
    depends_on: [ rabbitmq ]

  gateway:
    build: ./services/gateway
    ports: [ "8080:8080" ]
    environment:
      AUTH_SERVICE_URL: http://auth-service:4001
      CATALOG_SERVICE_URL: http://catalog-service:4002
      ORDER_SERVICE_URL: http://order-service:4003
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-dev-access-secret}
    depends_on: [ postgres, auth-service, catalog-service, order-service ]

  frontend:
    build: ./frontend
    ports: [ "3002:80" ]
    depends_on: [ gateway ]

volumes:
  pgdata:
